# Exported from Render on 2024-07-17T16:53:21Z
services:
- type: web
  name: Travel-2
  runtime: node
  repo: https://github.com/Sushant0124/Travel
  plan: free
  envVars:
  - key: SECRET
    sync: false
  - key: MONGO_URL
    sync: false
  - key: MAP_KEY
    sync: false
  - key: API_SECRET
    sync: false
  - key: API_KEY
    sync: false
  - key: CLOUD_NAME
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node app.js
- type: web
  name: Travel-1
  runtime: node
  repo: https://github.com/Sushant0124/Travel
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: node app.js
- type: web
  name: Travel
  runtime: node
  repo: https://github.com/Sushant0124/Travel
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: node app.js
- type: web
  name: WanderLust
  runtime: node
  repo: https://github.com/Sushant0124/WanderLust
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: node app.js
- type: web
  name: A-Chit-Chat-App
  runtime: node
  repo: https://github.com/Sushant0124/A-Chit-Chat-App
  plan: free
  envVars:
  - key: PORT
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm start
- type: web
  name: E-commerce-1
  runtime: node
  repo: https://github.com/Sushant0124/E-commerce
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: node index.js
  autoDeploy: false
- type: web
  name: E-commerce
  runtime: node
  repo: https://github.com/Sushant0124/E-commerce
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: node index.js
version: "1"
